server:
  port: 5465
  servlet:
    context-path: /api                            # ! 测试/生产环境替换
    compression:
      enabled: true
      mime-types: application/javascript,application/json,application/xml,text/html,text/xml,text/plain,text/css,image/*

spring:
  application:
    name: ZLink
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/small_oms
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath*:work/sajor/**/*Mapper.xml
  typeAliasesPackage: work.sajor.**.entity
  typeEnumsPackage: work.sajor.**                  # enum 定义在实体扩展类内
  global-config:
    banner: false                                 # 关闭 MP3.0 自带的banner
    workerId: 1                                   # SnowFlake : 机器 ID
    datacenterId: 1                               # SnowFlake : 数据标识 ID
    db-config:
      id-type: ASSIGN_ID                          # 使用 SnowFlake. 主键类型  0:"数据库ID自增",1:"该类型为未设置主键类型", 2:"用户输入ID",3:"全局唯一ID (数字类型唯一ID)", 4:"全局唯一ID UUID",5:"字符串全局唯一ID (idWorker 的字符串表示)";
      table-underline: true                       # 默认数据库表下划线命名
      logic-delete-field: delete_flag             # 全局逻辑删除字段值 3.3.0开始支持，详情看下面。
      logic-delete-value: now()                   # 逻辑已删除值(默认为 1)
      logic-not-delete-value: "null"              # 逻辑未删除值(默认为 0)

logging:
  level:
    work.sajor: debug
    org.*: warn
    com.*: warn
    org.springframework.data: error
    org.springframework.boot.autoconfigure.orm.jpa: error
    work.sajor.crap.server: info
    work.sajor.crap.core.security.component: info
    work.sajor.crap.core.security.jwt: info
  file:
    path: /tmp/crap/log

crap:
  log:
    path: /tmp/crap/log